version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/evgenz_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=evgenz_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  admin-panel:
    build: ./admin-panel
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000

  redis:
    image: redis:alpine
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data:
